### ISSUE TITLE
Function mv=gapotParseMPV(mvText)

### ISSUE THREAD

**Issue by fmarrabal** [ga-explorer/GeometricAlgebraNumericsLib#1]
The function written in Matlab code:
function mv = gapotParseMPV(mvText)
    mv = GeometricAlgebraNumericsLib.Applications.GAPoT.GaPoTMultiPhaseVector.Parse(mvText);
end
does not work. I think, it is due to the new form of the variable parse declaration:

var mvU =  $"[{a1}<1>]<a>;[{a2}<3>]<b>".GaPoTNumParseMultiPhaseVector();

For using this in matlab, I think, we need a function or something like that.

**Comment by ga-explorer** [comment]
Fixed issue by replacing:
mv = GeometricAlgebraNumericsLib.Applications.GAPoT.GaPoTMultiPhaseVector.Parse(mvText);

With:
mv = GeometricAlgebraNumericsLib.Applications.GAPoT.GaPoTNumUtils.GaPoTNumParseMultiPhaseVector(mvText);

And made similar fix to function gapotParseSPV

Please confirm it works correctly now. Thanks

**Comment by fmarrabal** [comment]
Alles in ordnung
